name: Deploy
on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: ssh -vvv -i /home/zhenglab/.ssh/id_ed25519 -o IdentitiesOnly=yes -T git@github.com || true